# Pre-commit hooks configuration for Grundschule Timetabler
# See https://pre-commit.com for more information

default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  # Python hooks - Ruff for formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        files: ^backend/

  # General purpose hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.(md|markdown)$
      - id: end-of-file-fixer
        exclude: ^.*\.(svg|png|jpg|jpeg|gif)$
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
      - id: detect-private-key

  # Prevent direct commits to main branch
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
        stages: [pre-commit]

  # Local hooks for backend checks
  - repo: local
    hooks:
      - id: ty-check
        name: ty type check
        entry: bash -c 'cd backend && uvx --native-tls ty check'
        language: system
        types: [python]
        files: ^backend/.*\.py$
        pass_filenames: false
        require_serial: true
        verbose: true

      - id: pytest
        name: run tests
        entry: bash -c 'cd backend && uv run pytest --no-cov -x'
        language: system
        types: [python]
        files: ^backend/.*\.py$
        pass_filenames: false
        require_serial: true
        verbose: true

      - id: migration-check
        name: check database migrations
        entry: bash -c 'cd backend && uv run alembic check'
        language: system
        types: [python]
        files: ^backend/(alembic/.*|src/models/.*)\.py$
        pass_filenames: false
        require_serial: true
        verbose: true

  # Conventional commits validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

# Configuration for specific hooks
exclude: |
  (?x)^(
    backend/alembic/.*|
    backend/\.venv/.*|
    .*/__pycache__/.*|
    .*\.egg-info/.*|
    backend/uv\.lock
  )$
