version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: grundschule-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/grundschule_timetabler
      - VALKEY_URL=redis://valkey:6379/0
      - ENVIRONMENT=development
      - SECRET_KEY=development-secret-key-change-in-production
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/.venv  # Prevent overwriting venv
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - grundschule-network
    restart: unless-stopped
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: grundschule-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grundschule_timetabler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - grundschule-network
    restart: unless-stopped

  # Valkey (Redis alternative)
  valkey:
    image: valkey/valkey:7-alpine
    container_name: grundschule-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - grundschule-network
    restart: unless-stopped
    command: valkey-server --appendonly yes

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: grundschule-mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI
    networks:
      - grundschule-network
    restart: unless-stopped

  # Frontend (placeholder for future React app)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: grundschule-frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - VITE_API_URL=http://localhost:8000
  #   networks:
  #     - grundschule-network
  #   restart: unless-stopped

networks:
  grundschule-network:
    driver: bridge

volumes:
  postgres_data:
  valkey_data:
